default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch # SKIP=no-commit-to-branch pre-commit run
        args:
          - --branch=xxx
      - id: check-added-large-files
        args:
          - --maxkb=16384
          - --enforce-all
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
        exclude: \.ipynb$|package-lock.json
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        types_or:
          - python
          - pyi
        args:
          - --fix
      - id: ruff-format
        types_or:
          - python
          - pyi
